/**
 * Brand Concierge theme export (paste the JSON generated by Brand Concierge UI).
 *
 * This file intentionally assigns window.styleConfiguration. The web agent reads that object during bootstrap.
 *
 * IMPORTANT:
 * - Replace the placeholder below with your real exported configuration object.
 * - Keeping only `{}` often results in little/no UI because there is nothing to theme/configure.
 *
 * Troubleshooting checklist:
 * - Confirm Network tab loads this file as 200 from /profile-viewer/styleConfigurations.js.
 * - Confirm Alloy is initialized by Tags/Launch (`typeof window.alloy === "function"`).
 * - Confirm concierge agent loads (`window.adobe?.concierge?.bootstrap`).
 */
window.styleConfiguration = window.styleConfiguration || {
  metadata: {},
  behavior: {},
  disclaimer: {},
  text: {},
  arrays: {},
  assets: {},
  theme: {}
};
