/**
 * Build-info / version stamp for Cloud Functions.
 *
 * Loaded once per cold-start. Reads functions/version.json which is
 * generated by scripts/build-version.mjs as part of the predeploy hook.
 * Every function call to setCors() then automatically attaches the
 * X-Build-Sha / X-Build-Short-Sha / X-Build-Branch response headers,
 * which scripts/deploy-status.mjs reads to compare deployed Functions
 * against deployed Hosting.
 *
 * Falls back to safe placeholders if version.json is missing — e.g.
 * during local emulator runs before the first deploy. Never throws.
 */

'use strict';

const fs = require('fs');
const path = require('path');

let cached = null;

function load() {
  if (cached) return cached;
  const fallback = {
    gitSha: 'unknown',
    gitShortSha: 'unknown',
    gitBranch: 'unknown',
    deployedAt: null,
    deployedBy: null,
  };
  try {
    const raw = fs.readFileSync(path.join(__dirname, 'version.json'), 'utf8');
    const parsed = JSON.parse(raw);
    cached = {
      gitSha: parsed.gitSha || 'unknown',
      gitShortSha: parsed.gitShortSha || (parsed.gitSha ? String(parsed.gitSha).slice(0, 7) : 'unknown'),
      gitBranch: parsed.gitBranch || 'unknown',
      deployedAt: parsed.deployedAt || null,
      deployedBy: parsed.deployedBy || null,
    };
  } catch (_e) {
    cached = fallback;
  }
  return cached;
}

/**
 * Attach build-info headers to a function response. Safe to call multiple
 * times. Includes Access-Control-Expose-Headers so browser JS can read
 * the X-Build-* values via fetch().headers.get(...).
 */
function setBuildHeaders(res) {
  if (!res || typeof res.setHeader !== 'function') return;
  const v = load();
  try {
    res.setHeader('X-Build-Sha', v.gitSha);
    res.setHeader('X-Build-Short-Sha', v.gitShortSha);
    res.setHeader('X-Build-Branch', v.gitBranch);
    if (v.deployedAt) res.setHeader('X-Build-Deployed-At', v.deployedAt);

    // Browsers default to exposing only a small set of "simple" response
    // headers via fetch(). Append the X-Build-* names so scripts/deploy-status.mjs
    // and any in-page version pill can read them. Preserve any value the
    // caller may have already set (e.g. application-specific headers).
    const existing = String(res.getHeader('Access-Control-Expose-Headers') || '').trim();
    const ours = 'X-Build-Sha, X-Build-Short-Sha, X-Build-Branch, X-Build-Deployed-At';
    res.setHeader('Access-Control-Expose-Headers', existing ? `${existing}, ${ours}` : ours);
  } catch (_e) {
    // Header set failures (response already sent, etc.) are non-fatal —
    // build-info is observability, not correctness.
  }
}

module.exports = {
  load,
  setBuildHeaders,
};
