'use strict';

const TABLE = 'AGENTIC_TELECOM_PROFILE_CUSTOMER';
const COLUMNS = [
  'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
  'FIRSTNAME', 'LASTNAME', 'DATEOFBIRTH', 'GENDER', 'NATIONALITY', 'PRIMARYEMAIL', 'PRIMARYPHONE',
  'ADDRESSSTREET', 'ADDRESSCITY', 'ADDRESSPOSTALCODE', 'ADDRESSCOUNTRY', 'LIFETIMEVALUE', 'CUSTOMERSEGMENT',
  'PLANTIER', 'BUNDLETYPE', 'MONTHLYSPEND', 'DATAALLOWANCEGB', 'DATAUSAGEGB', 'CONTRACTSTARTDATE',
  'CONTRACTENDDATE', 'DEVICEMODEL', 'DEVICETIER', 'NETWORKNPS', 'TOTALCALLMINUTES', 'UPGRADEELIGIBLE',
  'LASTCONTACTDATE', 'LASTCONTACTREASON', 'CHURNRISK',
  'TESTPROFILE', '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
];
const NUMBER_COLUMNS = new Set([
  'LIFETIMEVALUE', 'MONTHLYSPEND', 'DATAALLOWANCEGB', 'DATAUSAGEGB', 'NETWORKNPS', 'TOTALCALLMINUTES', 'CHURNRISK',
]);
const COLUMN_DDL = COLUMNS.map((column) => {
  if (column === 'PUSHTOKENS') return `${column} ARRAY`;
  if (column === 'TESTPROFILE' || column === 'UPGRADEELIGIBLE') return `${column} BOOLEAN`;
  if (NUMBER_COLUMNS.has(column)) return `${column} NUMBER(18,2)`;
  return `${column} VARCHAR(320)`;
});

module.exports = { TABLE, COLUMNS, COLUMN_DDL };
