'use strict';

const TABLE = 'AGENTIC_RETAIL_PROFILE_CUSTOMER';
const COLUMNS = [
  'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
  'FIRSTNAME', 'LASTNAME', 'DATEOFBIRTH', 'GENDER', 'NATIONALITY', 'PRIMARYEMAIL', 'PRIMARYPHONE',
  'ADDRESSSTREET', 'ADDRESSCITY', 'ADDRESSPOSTALCODE', 'ADDRESSCOUNTRY', 'LIFETIMEVALUE', 'CUSTOMERSEGMENT',
  'TOTALORDERS', 'LASTORDERDATE', 'LASTORDERVALUE', 'FAVOURITECATEGORY', 'FAVOURITEBRAND',
  'LINKEDSTOREID', 'LINKEDSTORENAME', 'AVGORDERVALUE', 'RETURNRATE', 'COBRANDEDCARDMEMBER',
  'PREFERREDSIZE', 'PREFERREDCHANNEL', 'ORDERSYTD', 'REWARDPOINTS', 'LASTRETURNDATE',
  'TESTPROFILE', '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
];
const NUMBER_COLUMNS = new Set([
  'LIFETIMEVALUE', 'TOTALORDERS', 'LASTORDERVALUE', 'AVGORDERVALUE', 'RETURNRATE', 'ORDERSYTD', 'REWARDPOINTS',
]);
const COLUMN_DDL = COLUMNS.map((column) => {
  if (column === 'PUSHTOKENS') return `${column} ARRAY`;
  if (column === 'TESTPROFILE' || column === 'COBRANDEDCARDMEMBER') return `${column} BOOLEAN`;
  if (NUMBER_COLUMNS.has(column)) return `${column} NUMBER(18,2)`;
  return `${column} VARCHAR(320)`;
});

module.exports = { TABLE, COLUMNS, COLUMN_DDL };
