'use strict';

const TABLE = 'AGENTIC_FSI_PROFILE_CUSTOMER';
const COLUMNS = [
  'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
  'FIRSTNAME', 'LASTNAME', 'DATEOFBIRTH', 'GENDER', 'NATIONALITY', 'PRIMARYEMAIL', 'PRIMARYPHONE',
  'ADDRESSSTREET', 'ADDRESSCITY', 'ADDRESSPOSTALCODE', 'ADDRESSCOUNTRY', 'LIFETIMEVALUE', 'CUSTOMERSEGMENT',
  'HOUSEHOLDINCOME', 'CREDITSCOREBAND', 'CREDITSCORE', 'LIFESTAGE', 'EMPLOYMENTSTATUS', 'PRIMARYBANKINGCHANNEL',
  'TOTALACCOUNTS', 'CHECKINGBALANCE', 'SAVINGSBALANCE', 'MORTGAGEBALANCE', 'INVESTMENTVALUE',
  'CREDITCARDLIMIT', 'MONTHLYCREDITSPEND', 'NEXTRATERENEWDATE', 'LASTBRANCHVISIT', 'RISKRATING',
  'TESTPROFILE', '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
];
const NUMBER_COLUMNS = new Set([
  'LIFETIMEVALUE', 'HOUSEHOLDINCOME', 'CREDITSCORE', 'TOTALACCOUNTS', 'CHECKINGBALANCE', 'SAVINGSBALANCE',
  'MORTGAGEBALANCE', 'INVESTMENTVALUE', 'CREDITCARDLIMIT', 'MONTHLYCREDITSPEND',
]);
const COLUMN_DDL = COLUMNS.map((column) => {
  if (column === 'PUSHTOKENS') return `${column} ARRAY`;
  if (column === 'TESTPROFILE') return `${column} BOOLEAN`;
  if (NUMBER_COLUMNS.has(column)) return `${column} NUMBER(18,2)`;
  return `${column} VARCHAR(320)`;
});

module.exports = { TABLE, COLUMNS, COLUMN_DDL };
