'use strict';

const { normalizeSnowflakeIndustry } = require('./snowflakeIndustryProfileRegistry');

const IDENTITY_DDL = [
  'EMAIL VARCHAR(320)',
  'ECID VARCHAR(320)',
  'CRMID VARCHAR(320)',
];
const EVENT_META_DDL = [
  'EVENTID VARCHAR(320)',
  'GENERATIONID VARCHAR(320)',
  'TIMESTAMP VARCHAR(320)',
];
const PROFILE_META_DDL = ['GENERATIONID VARCHAR(320)'];
const RECORD_DDL = '_RECORDCREATEDTIMESTAMP VARCHAR(320)';

function columnName(ddl) {
  return String(ddl).trim().split(/\s+/)[0];
}

function table(industry, key, name, kind, fields) {
  const columnDdl = [
    ...IDENTITY_DDL,
    ...(kind === 'event' ? EVENT_META_DDL : PROFILE_META_DDL),
    ...fields,
    RECORD_DDL,
  ];
  return Object.freeze({
    industry,
    key,
    table: name,
    kind,
    columnDdl: Object.freeze(columnDdl),
    columns: Object.freeze(columnDdl.map(columnName)),
    arrayColumns: Object.freeze(
      fields.filter((field) => /\sARRAY$/i.test(field.trim())).map(columnName),
    ),
  });
}

/**
 * Travel tables predate this registry and already have a fixed, real column
 * layout (from the Python agentic-travel-runner INSERT statements) that
 * doesn't match the synthetic identity/meta layout `table()` assembles for
 * fsi/retail/telecom/media/sports. This variant takes the exact column list
 * as-is — used only for read-back (profile bundle), never for provisioning
 * or enrich-insert, so `columnDdl` here is a harmless placeholder.
 */
function travelTable(key, name, kind, columns) {
  return Object.freeze({
    industry: 'travel',
    key,
    table: name,
    kind,
    columnDdl: Object.freeze(columns.map((column) => `${column} VARCHAR(320)`)),
    columns: Object.freeze(columns.slice()),
    arrayColumns: Object.freeze([]),
  });
}

const INDUSTRY_EVENT_CONFIG = Object.freeze({
  fsi: Object.freeze({
    digital: table('fsi', 'digital', 'AGENTIC_FSI_EVENT_DIGITAL', 'event', [
      'CHANNEL VARCHAR(320)', 'ACTION VARCHAR(320)', 'AMOUNT NUMBER(18,2)',
      'CURRENCY VARCHAR(10)', 'DEVICE VARCHAR(320)', 'SESSION_DURATION_SECONDS NUMBER(18,0)',
      'IP_COUNTRY VARCHAR(320)', 'AUTHENTICATION_METHOD VARCHAR(320)',
    ]),
    transaction: table('fsi', 'transaction', 'AGENTIC_FSI_EVENT_TRANSACTION', 'event', [
      'TRANSACTION_TYPE VARCHAR(320)', 'DIRECTION VARCHAR(10)', 'AMOUNT NUMBER(18,2)',
      'CURRENCY VARCHAR(10)', 'MERCHANT VARCHAR(320)', 'CATEGORY VARCHAR(320)',
      'BALANCE_AFTER NUMBER(18,2)', 'ACCOUNT_TYPE VARCHAR(320)', 'REFERENCE VARCHAR(320)',
    ]),
    application: table('fsi', 'application', 'AGENTIC_FSI_EVENT_APPLICATION', 'event', [
      'APPLICATION_ID VARCHAR(320)', 'PRODUCT_TYPE VARCHAR(320)', 'STAGE VARCHAR(320)',
      'AMOUNT_REQUESTED NUMBER(18,2)', 'TERM_MONTHS NUMBER(18,0)', 'CHANNEL VARCHAR(320)',
      'DECISION_REASON VARCHAR(320)',
    ]),
    advisory: table('fsi', 'advisory', 'AGENTIC_FSI_EVENT_ADVISORY', 'event', [
      'CHANNEL VARCHAR(320)', 'ADVISOR_ID VARCHAR(320)', 'TOPIC VARCHAR(320)',
      'DURATION_MINUTES NUMBER(18,0)', 'OUTCOME VARCHAR(320)', 'NEXT_ACTION_DATE VARCHAR(320)',
      'NPS_SCORE NUMBER(18,0)',
    ]),
    products: table('fsi', 'products', 'AGENTIC_FSI_PROFILE_PRODUCTS', 'enrichment', [
      'PRODUCT_TYPE VARCHAR(320)', 'ACCOUNT_NUMBER VARCHAR(320)', 'OPEN_DATE VARCHAR(320)',
      'BALANCE NUMBER(18,2)', 'INTEREST_RATE NUMBER(8,4)', 'TERM_END_DATE VARCHAR(320)',
      'MONTHLY_PAYMENT NUMBER(18,2)', 'STATUS VARCHAR(320)',
    ]),
  }),
  retail: Object.freeze({
    order: table('retail', 'order', 'AGENTIC_RETAIL_EVENT_ORDER', 'event', [
      'ORDER_ID VARCHAR(320)', 'ITEMS ARRAY', 'ITEM_COUNT NUMBER(18,0)',
      'ORDER_TOTAL NUMBER(18,2)', 'CURRENCY VARCHAR(10)', 'PAYMENT_METHOD VARCHAR(320)',
      'CHANNEL VARCHAR(320)', 'DELIVERY_METHOD VARCHAR(320)', 'STATUS VARCHAR(320)',
      'PROMO_CODE VARCHAR(320)',
    ]),
    browse: table('retail', 'browse', 'AGENTIC_RETAIL_EVENT_BROWSE', 'event', [
      'PAGE_TYPE VARCHAR(320)', 'PRODUCT_ID VARCHAR(320)', 'PRODUCT_NAME VARCHAR(320)',
      'CATEGORY VARCHAR(320)', 'DWELL_TIME_SECONDS NUMBER(18,0)', 'DEVICE VARCHAR(320)',
      'SEARCH_TERM VARCHAR(320)', 'REFERRAL_SOURCE VARCHAR(320)',
    ]),
    return: table('retail', 'return', 'AGENTIC_RETAIL_EVENT_RETURN', 'event', [
      'RETURN_ID VARCHAR(320)', 'ORDER_ID VARCHAR(320)', 'ITEMS ARRAY',
      'REASON VARCHAR(320)', 'REFUND_AMOUNT NUMBER(18,2)', 'METHOD VARCHAR(320)',
      'STATUS VARCHAR(320)',
    ]),
    service: table('retail', 'service', 'AGENTIC_RETAIL_EVENT_SERVICE', 'event', [
      'CASE_ID VARCHAR(320)', 'CHANNEL VARCHAR(320)', 'TOPIC VARCHAR(320)',
      'RESOLUTION VARCHAR(320)', 'CSAT_SCORE NUMBER(18,0)', 'RESPONSE_TIME_MINUTES NUMBER(18,0)',
    ]),
    rewards: table('retail', 'rewards', 'AGENTIC_RETAIL_PROFILE_REWARDS', 'enrichment', [
      'TIER VARCHAR(320)', 'POINTS_BALANCE NUMBER(18,0)', 'POINTS_EARNED_YTD NUMBER(18,0)',
      'POINTS_REDEEMED_YTD NUMBER(18,0)', 'TIER_EXPIRY_DATE VARCHAR(320)',
      'NEXT_TIER_THRESHOLD NUMBER(18,0)', 'PREFERRED_REWARD_TYPE VARCHAR(320)',
      'BIRTHDAY_REWARD_USED BOOLEAN', 'REFERRAL_COUNT NUMBER(18,0)',
    ]),
  }),
  telecom: Object.freeze({
    usage: table('telecom', 'usage', 'AGENTIC_TELECOM_EVENT_USAGE', 'event', [
      'USAGE_TYPE VARCHAR(320)', 'DURATION_SECONDS NUMBER(18,0)', 'DATA_MB NUMBER(18,2)',
      'DESTINATION VARCHAR(320)', 'ROAMING BOOLEAN', 'NETWORK_TYPE VARCHAR(320)',
      'PEAK_FLAG BOOLEAN',
    ]),
    billing: table('telecom', 'billing', 'AGENTIC_TELECOM_EVENT_BILLING', 'event', [
      'INVOICE_ID VARCHAR(320)', 'AMOUNT NUMBER(18,2)', 'CURRENCY VARCHAR(10)',
      'PAYMENT_STATUS VARCHAR(320)', 'PAYMENT_METHOD VARCHAR(320)', 'OVERDUE_DAYS NUMBER(18,0)',
      'BILL_PERIOD_START VARCHAR(320)', 'BILL_PERIOD_END VARCHAR(320)',
    ]),
    service: table('telecom', 'service', 'AGENTIC_TELECOM_EVENT_SERVICE', 'event', [
      'CASE_ID VARCHAR(320)', 'CHANNEL VARCHAR(320)', 'TOPIC VARCHAR(320)',
      'RESOLUTION VARCHAR(320)', 'NPS_SCORE NUMBER(18,0)', 'AGENT_ID VARCHAR(320)',
      'CALL_DURATION_SECONDS NUMBER(18,0)',
    ]),
    network: table('telecom', 'network', 'AGENTIC_TELECOM_EVENT_NETWORK', 'event', [
      'EVENT_TYPE VARCHAR(320)', 'CELL_ID VARCHAR(320)', 'DURATION_MINUTES NUMBER(18,0)',
      'IMPACT_AREA VARCHAR(320)', 'DOWNLOAD_SPEED_MBPS NUMBER(18,2)',
      'UPLOAD_SPEED_MBPS NUMBER(18,2)',
    ]),
    devices: table('telecom', 'devices', 'AGENTIC_TELECOM_PROFILE_DEVICES', 'enrichment', [
      'DEVICE_MODEL VARCHAR(320)', 'IMEI VARCHAR(320)', 'ACTIVATION_DATE VARCHAR(320)',
      'TRADE_IN_VALUE NUMBER(18,2)', 'INSURANCE BOOLEAN', 'INSURANCE_TIER VARCHAR(320)',
      'UPGRADE_ELIGIBLE_DATE VARCHAR(320)', 'PREVIOUS_DEVICE VARCHAR(320)',
      'CONTRACT_MONTHS NUMBER(18,0)', 'STATUS VARCHAR(320)',
    ]),
  }),
  media: Object.freeze({
    viewing: table('media', 'viewing', 'AGENTIC_MEDIA_EVENT_VIEWING', 'event', [
      'CONTENT_ID VARCHAR(320)', 'TITLE VARCHAR(320)', 'CONTENT_TYPE VARCHAR(320)',
      'GENRE VARCHAR(320)', 'SEASON NUMBER(18,0)', 'EPISODE NUMBER(18,0)',
      'DURATION_WATCHED_MINUTES NUMBER(18,0)', 'TOTAL_DURATION_MINUTES NUMBER(18,0)',
      'COMPLETION_PCT NUMBER(8,2)', 'DEVICE VARCHAR(320)', 'STREAM_QUALITY VARCHAR(320)',
      'PROFILE_NAME VARCHAR(320)',
    ]),
    engagement: table('media', 'engagement', 'AGENTIC_MEDIA_EVENT_ENGAGEMENT', 'event', [
      'ACTION VARCHAR(320)', 'CONTENT_ID VARCHAR(320)', 'TITLE VARCHAR(320)',
      'RATING NUMBER(8,1)', 'SHARE_PLATFORM VARCHAR(320)',
    ]),
    billing: table('media', 'billing', 'AGENTIC_MEDIA_EVENT_BILLING', 'event', [
      'EVENT_TYPE VARCHAR(320)', 'PLAN VARCHAR(320)', 'AMOUNT NUMBER(18,2)',
      'CURRENCY VARCHAR(10)', 'PAYMENT_METHOD VARCHAR(320)', 'PAYMENT_STATUS VARCHAR(320)',
      'ADDONS ARRAY',
    ]),
    download: table('media', 'download', 'AGENTIC_MEDIA_EVENT_DOWNLOAD', 'event', [
      'CONTENT_ID VARCHAR(320)', 'TITLE VARCHAR(320)', 'CONTENT_TYPE VARCHAR(320)',
      'FILE_SIZE_MB NUMBER(18,2)', 'DEVICE VARCHAR(320)', 'EXPIRY_DATE VARCHAR(320)',
      'STATUS VARCHAR(320)',
    ]),
    watchlist: table('media', 'watchlist', 'AGENTIC_MEDIA_PROFILE_WATCHLIST', 'enrichment', [
      'CONTENT_ID VARCHAR(320)', 'TITLE VARCHAR(320)', 'GENRE VARCHAR(320)',
      'CONTENT_TYPE VARCHAR(320)', 'ADDED_DATE VARCHAR(320)', 'PRIORITY NUMBER(18,0)',
      'ESTIMATED_DURATION_MINUTES NUMBER(18,0)', 'STATUS VARCHAR(320)',
    ]),
  }),
  sports: Object.freeze({
    attendance: table('sports', 'attendance', 'AGENTIC_SPORTS_EVENT_ATTENDANCE', 'event', [
      'EVENT_ID VARCHAR(320)', 'EVENT_NAME VARCHAR(320)', 'SPORT VARCHAR(320)',
      'VENUE VARCHAR(320)', 'SECTION VARCHAR(320)', 'TICKET_TYPE VARCHAR(320)',
      'TICKET_PRICE NUMBER(18,2)', 'COMPANIONS NUMBER(18,0)', 'GATE_SCAN_TIME VARCHAR(320)',
    ]),
    merchandise: table('sports', 'merchandise', 'AGENTIC_SPORTS_EVENT_MERCHANDISE', 'event', [
      'ORDER_ID VARCHAR(320)', 'ITEMS ARRAY', 'ITEM_COUNT NUMBER(18,0)',
      'ORDER_TOTAL NUMBER(18,2)', 'CURRENCY VARCHAR(10)', 'CHANNEL VARCHAR(320)',
      'PAYMENT_METHOD VARCHAR(320)', 'PERSONALISATION BOOLEAN',
    ]),
    engagement: table('sports', 'engagement', 'AGENTIC_SPORTS_EVENT_ENGAGEMENT', 'event', [
      'ACTION VARCHAR(320)', 'CONTEXT VARCHAR(320)', 'PLATFORM VARCHAR(320)',
      'POINTS_EARNED NUMBER(18,0)', 'RESULT VARCHAR(320)',
    ]),
    betting: table('sports', 'betting', 'AGENTIC_SPORTS_EVENT_BETTING', 'event', [
      'EVENT_ID VARCHAR(320)', 'EVENT_NAME VARCHAR(320)', 'BET_TYPE VARCHAR(320)',
      'STAKE NUMBER(18,2)', 'ODDS NUMBER(18,2)', 'OUTCOME VARCHAR(320)',
      'PAYOUT NUMBER(18,2)', 'BOOKMAKER VARCHAR(320)',
    ]),
    membership: table('sports', 'membership', 'AGENTIC_SPORTS_PROFILE_MEMBERSHIP', 'enrichment', [
      'MEMBERSHIP_TYPE VARCHAR(320)', 'MEMBER_SINCE VARCHAR(320)', 'RENEWAL_DATE VARCHAR(320)',
      'AUTO_RENEW BOOLEAN', 'ANNUAL_FEE NUMBER(18,2)', 'BENEFITS_USED ARRAY',
      'LOYALTY_POINTS NUMBER(18,0)', 'REFERRALS_MADE NUMBER(18,0)', 'STATUS VARCHAR(320)',
    ]),
  }),
  // Read-only registration of Travel's existing phase 1-3 tables so
  // `handleIndustryProfileBundle` can read them back too — Travel's
  // generate/enrich still go through the Python agentic-travel-runner and
  // never touch this registry for writes. Column lists are copied verbatim
  // from the runner's own INSERT statements (services/agentic-travel-runner/py/).
  travel: Object.freeze({
    baseProfile: travelTable('baseProfile', 'AGENTIC_TRAVEL_PROFILE_CUSTOMER_BASE_PROFILE', 'profile', [
      'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'FIRSTNAME', 'LASTNAME', 'BIRTHDATE', 'GENDER',
      'HOMEADDRESS_STREET1', 'HOMEADDRESS_CITY', 'HOMEADDRESS_STATEPROVINCE', 'HOMEADDRESS_POSTALCODE', 'HOMEADDRESS_COUNTRY',
      'PERSONALEMAIL_ADDRESS', 'PERSONALEMAIL_LABEL', 'PERSONALEMAIL_PRIMARY', 'PERSONALEMAIL_STATUS', 'PERSONALEMAIL_STATUSREASON', 'PERSONALEMAIL_TYPE',
      'MOBILEPHONE_NUMBER', 'MOBILEPHONE_STATUS', 'MOBILEPHONE_PRIMARY',
      'TESTPROFILE', '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
      'PERSON_NAME_COURTESYTITLE', 'PERSON_NAME_SUFFIX', 'PERSON_NAME_FULLNAME',
      'PERSON_BIRTHDAY', 'PERSON_BIRTHMONTH', 'PERSON_BIRTHYEAR', 'PERSON_BIRTHDAYANDMONTH',
    ]),
    customer: travelTable('customer', 'AGENTIC_TRAVEL_PROFILE_CUSTOMER', 'profile', [
      'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'FIRSTNAME', 'LASTNAME', 'DATEOFBIRTH', 'GENDER', 'NATIONALITY', 'PRIMARYEMAIL', 'PRIMARYPHONE',
      'ADDRESSSTREET', 'ADDRESSCITY', 'ADDRESSPOSTALCODE', 'ADDRESSCOUNTRY',
      'LASTHOLIDAYDATE', 'LASTHOLIDAYDESTINATION', 'UPCOMINGHOLIDAYDATE', 'UPCOMINGHOLIDAYDESTINATION',
      'TOTALFLIGHTSTAKEN', 'TOTALDISTANCEFLOWN', 'FAVORITEDESTINATIONS',
      'PREFERREDCABINCLASS', 'PREFERREDSEATTYPE', 'MEALPREFERENCE', 'SPECIALASSISTANCE',
      'LIFETIMEVALUE', 'AVERAGEBOOKINGVALUE', 'TOTALBOOKINGS', 'CUSTOMERSEGMENT',
      'TESTPROFILE', '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
    ]),
    website: travelTable('website', 'AGENTIC_TRAVEL_EVENT_WEBSITE', 'event', [
      'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'PAGEURL', 'PAGENAME', 'PAGETYPE', 'REFERRER', 'SEARCHTERM',
      'ORIGINAIRPORT', 'DESTINATIONAIRPORT', 'DEPARTUREDATE', 'RETURNDATE', 'PASSENGERCOUNT', 'CABINCLASS', 'RESULTSCOUNT',
      'FLIGHTNUMBER', 'FLIGHTORIGIN', 'FLIGHTDESTINATION', 'FLIGHTDEPARTURETIME', 'FLIGHTPRICE', 'FLIGHTCURRENCY',
      'ACTION', 'ELEMENTCLICKED', 'TIMEONPAGE', 'SESSIONID', 'DEVICETYPE', 'BROWSER', 'OPERATINGSYSTEM',
      '_RECORDCREATEDTIMESTAMP', 'MARKETING_CHANNEL', 'MARKETING_CHANNEL_DETAIL', 'CAMPAIGN_ID', 'CAMPAIGN_NAME', 'CAMPAIGN_TYPE',
      'UTM_SOURCE', 'UTM_MEDIUM', 'UTM_CAMPAIGN', 'UTM_CONTENT', 'UTM_TERM', 'REFERRER_DOMAIN', 'REFERRER_TYPE',
      'FUNNEL_NAME', 'FUNNEL_STEP', 'FUNNEL_STEP_NUMBER', 'FUNNEL_COMPLETION_STATUS',
      'ANCILLARY_ITEM_NAME', 'ANCILLARY_ITEM_PRICE', 'ANCILLARY_ITEM_CATEGORY', 'CHANNEL',
    ]),
    booking: travelTable('booking', 'AGENTIC_TRAVEL_EVENT_BOOKING', 'event', [
      'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'PNR', 'BOOKINGSTATUS', 'BOOKINGDATE', 'BOOKINGCHANNEL', 'TRIPTYPE',
      'OUTBOUNDFLIGHTNUMBER', 'OUTBOUNDORIGIN', 'OUTBOUNDDESTINATION', 'OUTBOUNDDEPARTUREDATE', 'OUTBOUNDARRIVALDATE', 'OUTBOUNDCABINCLASS',
      'RETURNFLIGHTNUMBER', 'RETURNORIGIN', 'RETURNDESTINATION', 'RETURNDEPARTUREDATE', 'RETURNARRIVALDATE', 'RETURNCABINCLASS',
      'TOTALPASSENGERS', 'ADULTCOUNT', 'CHILDCOUNT', 'INFANTCOUNT',
      'TOTALPRICE', 'BASEFARE', 'TAXES', 'FEES', 'CURRENCY', 'DISCOUNTAPPLIED', 'LOYALTYPOINTSUSED', 'LOYALTYPOINTSEARNED',
      'PAYMENTMETHOD', 'CARDTYPE', 'TRANSACTIONID', 'PAYMENTSTATUS',
      'BAGGAGECOUNT', 'SEATSELECTION', 'MEALSELECTION', 'INSURANCE', 'FASTTRACK', 'LOUNGEACCESS',
      '_RECORDCREATEDTIMESTAMP', 'MARKETING_CHANNEL', 'MARKETING_CHANNEL_DETAIL', 'CAMPAIGN_ID', 'CAMPAIGN_NAME', 'CAMPAIGN_TYPE',
      'UTM_SOURCE', 'UTM_MEDIUM', 'UTM_CAMPAIGN', 'UTM_CONTENT', 'UTM_TERM', 'REFERRER_DOMAIN', 'REFERRER_TYPE',
      'PRODUCT_FINDING_METHOD', 'PRODUCT_SEARCH_TERM', 'PRODUCT_CATEGORY', 'PRODUCT_LIST_NAME', 'PRODUCT_POSITION',
      'CROSS_SELL_SOURCE', 'RECOMMENDATION_ALGORITHM',
      'TOUCHPOINTS_BEFORE_CONVERSION', 'DAYS_TO_CONVERSION', 'FIRST_TOUCH_CHANNEL', 'FIRST_TOUCH_TIMESTAMP',
      'LAST_TOUCH_CHANNEL', 'ASSIST_CHANNELS', 'CHANNEL_PATH', 'IS_FIRST_TIME_CUSTOMER', 'PREVIOUS_BOOKING_COUNT', 'CHANNEL',
    ]),
    mobile: travelTable('mobile', 'AGENTIC_TRAVEL_EVENT_MOBILE', 'event', [
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'MOBILE_APP_VERSION', 'MOBILE_PLATFORM', 'MOBILE_OS_VERSION', 'MOBILE_DEVICE_MODEL', 'MOBILE_SESSION_ID', 'MOBILE_SESSION_DURATION',
      'MOBILE_IS_FIRST_LAUNCH', 'MOBILE_IS_AUTHENTICATED', 'MOBILE_INTERACTION_TYPE', 'MOBILE_SCREEN_NAME', 'MOBILE_PREVIOUS_SCREEN',
      'MOBILE_SEARCH_TERM', 'MOBILE_SEARCH_TYPE', 'MOBILE_SEARCH_ORIGIN', 'MOBILE_SEARCH_DESTINATION', 'MOBILE_SEARCH_DEPARTURE_DATE',
      'MOBILE_SEARCH_RETURN_DATE', 'MOBILE_SEARCH_PASSENGERS', 'MOBILE_SEARCH_CABIN_CLASS', 'MOBILE_SEARCH_RESULTS_COUNT',
      'MOBILE_PRODUCT_TYPE', 'MOBILE_PRODUCT_FLIGHT_NUMBER', 'MOBILE_PRODUCT_AIRLINE', 'MOBILE_PRODUCT_PRICE', 'MOBILE_PRODUCT_CURRENCY', 'MOBILE_PRODUCT_AVAILABILITY',
      'MOBILE_CART_ACTION', 'MOBILE_CART_VALUE', 'MOBILE_CART_ITEM_COUNT',
      'MOBILE_NOTIFICATION_ID', 'MOBILE_NOTIFICATION_TYPE', 'MOBILE_NOTIFICATION_ACTION',
      'MOBILE_SCROLL_DEPTH', 'MOBILE_TIME_ON_SCREEN', 'MOBILE_INTERACTION_COUNT',
      'MARKETING_CHANNEL', 'MARKETING_CHANNEL_DETAIL', 'CAMPAIGN_ID', 'CAMPAIGN_NAME', 'CAMPAIGN_TYPE',
      'UTM_SOURCE', 'UTM_MEDIUM', 'UTM_CAMPAIGN', 'UTM_CONTENT', 'UTM_TERM', 'REFERRER_DOMAIN', 'REFERRER_TYPE',
      'FUNNEL_NAME', 'FUNNEL_STEP', 'FUNNEL_STEP_NUMBER', 'FUNNEL_COMPLETION_STATUS',
      'ANCILLARY_ITEM_NAME', 'ANCILLARY_ITEM_PRICE', 'ANCILLARY_ITEM_CATEGORY', 'CHANNEL', '_RECORDCREATEDTIMESTAMP',
    ]),
    call: travelTable('call', 'AGENTIC_TRAVEL_EVENT_CALLCENTRE', 'event', [
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'CALL_ID', 'CALL_DURATION', 'CALL_QUEUE_TIME', 'CALL_DIRECTION', 'CALL_CHANNEL', 'CALL_PRIMARY_REASON', 'CALL_SECONDARY_REASON', 'CALL_URGENCY',
      'CALL_AGENT_ID', 'CALL_AGENT_NAME', 'CALL_AGENT_TEAM', 'CALL_AGENT_LOCATION',
      'CALL_RESOLUTION_STATUS', 'CALL_RESOLUTION_TIME', 'CALL_FIRST_CALL_RESOLUTION', 'CALL_FOLLOW_UP_REQUIRED',
      'CALL_COMPENSATION_OFFERED', 'CALL_COMPENSATION_AMOUNT', 'CALL_SATISFACTION_SCORE', 'CALL_NPS_SCORE', 'CALL_FEEDBACK_PROVIDED',
      'CHANNEL', '_RECORDCREATEDTIMESTAMP',
    ]),
    checkin: travelTable('checkin', 'AGENTIC_TRAVEL_EVENT_CHECKIN', 'event', [
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'CHECKIN_METHOD', 'CHECKIN_TIME', 'CHECKIN_HOURS_BEFORE_DEPARTURE', 'CHECKIN_LOCATION',
      'CHECKIN_SEAT_NUMBER', 'CHECKIN_SEAT_TYPE', 'CHECKIN_SEAT_LOCATION', 'CHECKIN_SEAT_UPGRADED', 'CHECKIN_SEAT_CHANGED', 'CHECKIN_SEAT_EXTRA_LEGROOM',
      'CHECKIN_CHECKED_BAGS', 'CHECKIN_TOTAL_WEIGHT', 'CHECKIN_OVERWEIGHT_BAGS', 'CHECKIN_BAGGAGE_FEES', 'CHECKIN_SPECIAL_ITEMS',
      'CHECKIN_BOARDING_PASS_NUMBER', 'CHECKIN_BOARDING_GROUP', 'CHECKIN_BOARDING_POSITION', 'CHECKIN_GATE_NUMBER', 'CHECKIN_BOARDING_TIME',
      'CHECKIN_DIGITAL_BOARDING_PASS', 'CHECKIN_MOBILE_WALLET_ADDED',
      'FUNNEL_NAME', 'FUNNEL_STEP', 'FUNNEL_STEP_NUMBER', 'FUNNEL_COMPLETION_STATUS',
      'ANCILLARY_ITEM_NAME', 'ANCILLARY_ITEM_PRICE', 'ANCILLARY_ITEM_CATEGORY', 'CHANNEL', '_RECORDCREATEDTIMESTAMP',
    ]),
    disruption: travelTable('disruption', 'AGENTIC_TRAVEL_EVENT_DISRUPTION', 'event', [
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'DISRUPTION_TYPE', 'DISRUPTION_SEVERITY', 'ORIGINAL_DEPARTURE_TIME', 'NEW_DEPARTURE_TIME', 'DELAY_MINUTES', 'DISRUPTION_REASON', 'NOTIFICATION_METHOD',
      'FLIGHT_NUMBER', 'AIRLINE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'ORIGINAL_GATE', 'NEW_GATE', 'AIRCRAFT',
      'MISSED_CONNECTION', 'REBOOKED_FLIGHT', 'COMPENSATION_OFFERED', 'COMPENSATION_TYPE', 'COMPENSATION_AMOUNT',
      'LOUNGE_ACCESS_PROVIDED', 'HOTEL_ACCOMMODATION_PROVIDED', 'CUSTOMER_CONTACTED', 'CONTACT_CHANNEL', 'RESPONSE_TIME',
      'RESOLUTION_OFFERED', 'CUSTOMER_ACCEPTED', 'CHANNEL', '_RECORDCREATEDTIMESTAMP',
    ]),
    inflight: travelTable('inflight', 'AGENTIC_TRAVEL_EVENT_INFLIGHT', 'event', [
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'FLIGHT_NUMBER', 'AIRLINE', 'ROUTE', 'CABIN_CLASS', 'SEAT_NUMBER', 'FLIGHT_DURATION',
      'INTERACTION_TYPE', 'CREW_MEMBER_ID', 'SERVICE_RATING', 'ITEM_ORDERED', 'SPECIAL_REQUEST', 'REQUEST_FULFILLED',
      'ENTERTAINMENT_SYSTEM_USED', 'CONTENT_TYPE', 'CONTENT_TITLE', 'WATCH_TIME', 'CONTENT_RATING',
      'MEAL_TYPE', 'MEAL_CHOICE', 'SPECIAL_MEAL', 'MEAL_RATING', 'EXTRA_ITEMS',
      'WIFI_PURCHASED', 'WIFI_PACKAGE', 'WIFI_COST', 'DATA_USED',
      'AMENITY_KIT_RECEIVED', 'BLANKET_REQUESTED', 'PILLOW_REQUESTED', 'TEMPERATURE_ADJUSTMENT', 'SEAT_COMFORT_RATING',
      'CHANNEL', '_RECORDCREATEDTIMESTAMP',
    ]),
    hotel: travelTable('hotel', 'AGENTIC_TRAVEL_EVENT_HOTEL', 'event', [
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'CONFIRMATION_NUMBER', 'HOTEL_CHAIN', 'HOTEL_NAME', 'HOTEL_LOCATION', 'CHECK_IN_DATE', 'CHECK_OUT_DATE', 'NIGHTS_STAY',
      'ROOM_TYPE', 'ROOM_NUMBER', 'RATE_CODE', 'TOTAL_COST',
      'CHECK_IN_METHOD', 'CHECK_IN_TIME', 'QUEUE_TIME', 'EARLY_CHECK_IN', 'ROOM_READY', 'UPGRADED_ROOM', 'WELCOME_AMENITIES',
      'ROOM_SERVICE_INTERACTION_TYPE', 'ORDER_TIME', 'DELIVERY_TIME', 'ITEMS_ORDERED', 'ORDER_TOTAL', 'SERVICE_RATING',
      'AMENITY_TYPE', 'USAGE_TIME', 'DURATION', 'ADDITIONAL_CHARGE', 'SATISFACTION_RATING',
      'HOUSEKEEPING_SERVICE_REQUESTED', 'DO_NOT_DISTURB', 'EXTRA_TOWELS', 'EXTRA_AMENITIES', 'CLEANLINESS_RATING',
      'CHECK_OUT_METHOD', 'CHECK_OUT_TIME', 'LATE_CHECK_OUT', 'FINAL_BILL_AMOUNT', 'INCIDENTAL_CHARGES', 'OVERALL_RATING',
      'CHANNEL', '_RECORDCREATEDTIMESTAMP',
    ]),
    loyalty: travelTable('loyalty', 'AGENTIC_TRAVEL_EVENT_LOYALTY', 'event', [
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'TRANSACTION_TYPE', 'TRANSACTION_ID', 'TRANSACTION_DATE', 'POINTS_AMOUNT', 'POINTS_BALANCE', 'TRANSACTION_REASON',
      'BASE_POINTS', 'BONUS_POINTS', 'TIER_MULTIPLIER', 'PROMOTION_CODE', 'PARTNER_POINTS', 'PARTNER_NAME',
      'REDEMPTION_TYPE', 'POINTS_REDEEMED', 'REDEMPTION_VALUE', 'BOOKING_REFERENCE', 'REDEMPTION_STATUS',
      'TIER_CHANGE_TRIGGERED', 'PREVIOUS_TIER', 'NEW_TIER', 'TIER_QUALIFYING_POINTS', 'TIER_BONUS_AWARDED', 'TIER_BENEFITS_UNLOCKED',
      'VOUCHER_ISSUED', 'VOUCHER_TYPE', 'VOUCHER_CODE', 'VOUCHER_VALUE', 'EXPIRY_DATE', 'VOUCHER_USED',
      'CAMPAIGN_ID', 'CAMPAIGN_NAME', 'PROMOTION_TYPE', 'PROMOTION_POINTS', 'CHANNEL', '_RECORDCREATEDTIMESTAMP',
    ]),
    pos: travelTable('pos', 'AGENTIC_TRAVEL_EVENT_POS', 'event', [
      '_ID', 'TIMESTAMP', 'EVENTTYPE', 'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
      'TRANSACTION_ID', 'TRANSACTION_TYPE', 'TRANSACTION_DATE', 'LOCATION', 'TERMINAL_ID', 'STORE_NAME',
      'ITEMS', 'ITEM_CATEGORIES', 'ITEM_COUNT', 'SUBTOTAL', 'TAX', 'DISCOUNT', 'TOTAL', 'CURRENCY',
      'PAYMENT_METHOD', 'CARD_TYPE', 'LOYALTY_POINTS_USED', 'VOUCHER_USED', 'VOUCHER_CODE',
      'LOYALTY_CARD_SCANNED', 'LOYALTY_ID', 'POINTS_EARNED', 'TIER_DISCOUNT', 'MEMBER_OFFER', 'IS_DUTY_FREE', 'TAX_SAVINGS',
      'PICKUP_LOCATION', 'FLIGHT_NUMBER', 'STAFF_ID', 'STAFF_SERVICE_RATING', 'UPSELL_OFFERED', 'UPSELL_ACCEPTED',
      'FUNNEL_NAME', 'FUNNEL_STEP', 'FUNNEL_STEP_NUMBER', 'FUNNEL_COMPLETION_STATUS',
      'ANCILLARY_ITEM_NAME', 'ANCILLARY_ITEM_PRICE', 'ANCILLARY_ITEM_CATEGORY', 'CHANNEL', '_RECORDCREATEDTIMESTAMP',
    ]),
    loyaltyProfile: travelTable('loyaltyProfile', 'AGENTIC_TRAVEL_PROFILE_LOYALTY', 'enrichment', [
      'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID', 'TESTPROFILE',
      'LOYALTY_PROGRAM_NAME', 'LOYALTY_MEMBER_NUMBER', 'LOYALTY_MEMBER_SINCE', 'LOYALTY_PROGRAM_STATUS',
      'LOYALTY_CURRENT_TIER', 'LOYALTY_TIER_START_DATE', 'LOYALTY_TIER_EXPIRY_DATE', 'LOYALTY_LAST_TIER_UPDATE_DATE', 'LOYALTY_PREVIOUS_TIER',
      'LOYALTY_TIER_QUALIFYING_POINTS', 'LOYALTY_POINTS_TO_NEXT_TIER', 'LOYALTY_TOTAL_POINTS',
      'LOYALTY_LIFETIME_POINTS_EARNED', 'LOYALTY_LIFETIME_POINTS_REDEEMED', 'LOYALTY_POINTS_EXPIRING_SOON', 'LOYALTY_POINTS_EXPIRY_DATE',
      'LOYALTY_LAST_POINTS_EARNED_DATE', 'LOYALTY_LAST_POINTS_REDEEMED_DATE',
      'LOYALTY_LOUNGE_ACCESS', 'LOYALTY_LOUNGE_VISITS_REMAINING', 'LOYALTY_PRIORITY_BOARDING', 'LOYALTY_FREE_BAGGAGE_ALLOWANCE',
      'LOYALTY_SEAT_UPGRADE_ELIGIBLE', 'LOYALTY_COMPANION_TICKETS', 'LOYALTY_FAST_TRACK_SECURITY',
      'LOYALTY_FLIGHTS_THIS_YEAR', 'LOYALTY_FLIGHTS_LAST_YEAR', 'LOYALTY_SEGMENTS_FLOWN',
      'LOYALTY_TOTAL_SPEND', 'LOYALTY_AVERAGE_SPEND_PER_BOOKING', '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
    ]),
    preferences: travelTable('preferences', 'AGENTIC_TRAVEL_PROFILE_PREFERENCES', 'enrichment', [
      'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID', 'TESTPROFILE',
      'PREF_COMM_PREFERRED_CHANNEL', 'PREF_COMM_EMAIL_OPT_IN', 'PREF_COMM_SMS_OPT_IN', 'PREF_COMM_PUSH_OPT_IN',
      'PREF_COMM_PHONE_OPT_IN', 'PREF_COMM_MARKETING_OPT_IN', 'PREF_COMM_FREQUENCY', 'PREF_COMM_PREFERRED_LANGUAGE',
      'PREF_TRAVEL_SEAT_TYPE', 'PREF_TRAVEL_SEAT_LOCATION', 'PREF_TRAVEL_MEAL', 'PREF_TRAVEL_CABIN_CLASS',
      'PREF_TRAVEL_WILLING_TO_PAY_UPGRADE', 'PREF_TRAVEL_AIRLINES', 'PREF_TRAVEL_HOTEL_CHAINS',
      'PREF_ACCESS_WHEELCHAIR', 'PREF_ACCESS_SPECIAL_ASSISTANCE', 'PREF_ACCESS_ASSISTANCE_TYPES', 'PREF_ACCESS_MEDICAL_CONDITIONS',
      '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
    ]),
  }),
});

function getIndustryEventConfig(industry) {
  return INDUSTRY_EVENT_CONFIG[normalizeSnowflakeIndustry(industry)] || null;
}

function getIndustryEventTable(industry, key) {
  const config = getIndustryEventConfig(industry);
  return config ? config[String(key || '').trim().toLowerCase()] || null : null;
}

function listIndustryEventTables(industry) {
  return Object.values(getIndustryEventConfig(industry) || {});
}

function listIndustryEventTypes(industry) {
  return Object.keys(getIndustryEventConfig(industry) || {});
}

module.exports = {
  INDUSTRY_EVENT_CONFIG,
  getIndustryEventConfig,
  getIndustryEventTable,
  listIndustryEventTables,
  listIndustryEventTypes,
};
