'use strict';

const TABLE = 'AGENTIC_MEDIA_PROFILE_CUSTOMER';
const COLUMNS = [
  'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
  'FIRSTNAME', 'LASTNAME', 'DATEOFBIRTH', 'GENDER', 'NATIONALITY', 'PRIMARYEMAIL', 'PRIMARYPHONE',
  'ADDRESSSTREET', 'ADDRESSCITY', 'ADDRESSPOSTALCODE', 'ADDRESSCOUNTRY', 'LIFETIMEVALUE', 'CUSTOMERSEGMENT',
  'SUBSCRIPTIONTIER', 'SUBSCRIPTIONSTARTDATE', 'MONTHLYFEE', 'PRIMARYGENRE', 'PREFERREDDEVICE',
  'VIEWINGMINUTESMONTHLY', 'LASTVIEWEDDATE', 'LASTVIEWEDTITLE', 'DOWNLOADSPERMONTH',
  'ACCOUNTSHARING', 'ADSUPPORTED', 'LIVESPORTSPACKAGE', 'KIDPROFILEENABLED', 'CONTENTRATINGPREF',
  'TESTPROFILE', '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
];
const NUMBER_COLUMNS = new Set(['LIFETIMEVALUE', 'MONTHLYFEE', 'VIEWINGMINUTESMONTHLY', 'DOWNLOADSPERMONTH']);
const BOOL_COLUMNS = new Set(['TESTPROFILE', 'ADSUPPORTED', 'LIVESPORTSPACKAGE', 'KIDPROFILEENABLED']);
const COLUMN_DDL = COLUMNS.map((column) => {
  if (column === 'PUSHTOKENS') return `${column} ARRAY`;
  if (BOOL_COLUMNS.has(column)) return `${column} BOOLEAN`;
  if (NUMBER_COLUMNS.has(column)) return `${column} NUMBER(18,2)`;
  return `${column} VARCHAR(320)`;
});

module.exports = { TABLE, COLUMNS, COLUMN_DDL };
