'use strict';

/**
 * AGENTIC_TRAVEL_PROFILE_CUSTOMER table shape (39 columns).
 * Matches services/agentic-travel-runner/py/data_generator.py insert_profiles().
 * Dual-load + lab_snowflake_query_profiles target this table (not BASE_PROFILES).
 */
const COLUMNS = [
  'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID',
  'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
  'FIRSTNAME', 'LASTNAME', 'DATEOFBIRTH', 'GENDER', 'NATIONALITY',
  'PRIMARYEMAIL', 'PRIMARYPHONE', 'ADDRESSSTREET', 'ADDRESSCITY', 'ADDRESSPOSTALCODE',
  'ADDRESSCOUNTRY',
  'LASTHOLIDAYDATE', 'LASTHOLIDAYDESTINATION', 'UPCOMINGHOLIDAYDATE', 'UPCOMINGHOLIDAYDESTINATION',
  'TOTALFLIGHTSTAKEN', 'TOTALDISTANCEFLOWN', 'FAVORITEDESTINATIONS',
  'PREFERREDCABINCLASS', 'PREFERREDSEATTYPE', 'MEALPREFERENCE', 'SPECIALASSISTANCE',
  'LIFETIMEVALUE', 'AVERAGEBOOKINGVALUE', 'TOTALBOOKINGS', 'CUSTOMERSEGMENT',
  'TESTPROFILE',
  '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
];

module.exports = {
  COLUMNS,
};
