'use strict';

/** AgenticAI BASE_PROFILES table shape (38 columns). Shared by generator + AEP mapper. */
const COLUMNS = [
  'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PASSPORTID',
  'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
  'FIRSTNAME', 'LASTNAME', 'BIRTHDATE', 'GENDER',
  'HOMEADDRESS_STREET1', 'HOMEADDRESS_CITY', 'HOMEADDRESS_STATEPROVINCE',
  'HOMEADDRESS_POSTALCODE', 'HOMEADDRESS_COUNTRY',
  'PERSONALEMAIL_ADDRESS', 'PERSONALEMAIL_LABEL', 'PERSONALEMAIL_PRIMARY',
  'PERSONALEMAIL_STATUS', 'PERSONALEMAIL_STATUSREASON', 'PERSONALEMAIL_TYPE',
  'MOBILEPHONE_NUMBER', 'MOBILEPHONE_STATUS', 'MOBILEPHONE_PRIMARY',
  'TESTPROFILE',
  '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
  'PERSON_NAME_COURTESYTITLE', 'PERSON_NAME_SUFFIX', 'PERSON_NAME_FULLNAME',
  'PERSON_BIRTHDAY', 'PERSON_BIRTHMONTH', 'PERSON_BIRTHYEAR',
  'PERSON_BIRTHDAYANDMONTH',
];

const COLUMN_DDL = [
  'CRMID VARCHAR(64)', 'ECID VARCHAR(64)', 'EMAIL VARCHAR(320)',
  'EMAILIDSHA256 VARCHAR(128)', 'GAID VARCHAR(128)', 'LOYALTYID VARCHAR(64)',
  'PASSPORTID VARCHAR(64)', 'PHONENUMBER VARCHAR(40)', 'PUSHTOKENS ARRAY',
  'STACKCHATID VARCHAR(64)',
  'FIRSTNAME VARCHAR(100)', 'LASTNAME VARCHAR(100)',
  'BIRTHDATE VARCHAR(10)', 'GENDER VARCHAR(16)',
  'HOMEADDRESS_STREET1 VARCHAR(200)', 'HOMEADDRESS_CITY VARCHAR(100)',
  'HOMEADDRESS_STATEPROVINCE VARCHAR(100)', 'HOMEADDRESS_POSTALCODE VARCHAR(20)',
  'HOMEADDRESS_COUNTRY VARCHAR(100)',
  'PERSONALEMAIL_ADDRESS VARCHAR(320)', 'PERSONALEMAIL_LABEL VARCHAR(40)',
  'PERSONALEMAIL_PRIMARY BOOLEAN', 'PERSONALEMAIL_STATUS VARCHAR(40)',
  'PERSONALEMAIL_STATUSREASON VARCHAR(80)', 'PERSONALEMAIL_TYPE VARCHAR(40)',
  'MOBILEPHONE_NUMBER VARCHAR(40)', 'MOBILEPHONE_STATUS VARCHAR(40)',
  'MOBILEPHONE_PRIMARY BOOLEAN',
  'TESTPROFILE BOOLEAN',
  '_RECORDCREATEDTIMESTAMP VARCHAR(40)', '_RECORDUPDATEDTIMESTAMP VARCHAR(40)',
  'PERSON_NAME_COURTESYTITLE VARCHAR(40)', 'PERSON_NAME_SUFFIX VARCHAR(40)',
  'PERSON_NAME_FULLNAME VARCHAR(200)',
  'PERSON_BIRTHDAY NUMBER(2,0)', 'PERSON_BIRTHMONTH NUMBER(2,0)',
  'PERSON_BIRTHYEAR NUMBER(4,0)', 'PERSON_BIRTHDAYANDMONTH VARCHAR(5)',
];

module.exports = {
  COLUMNS,
  COLUMN_DDL,
};
