'use strict';

const TABLE = 'AGENTIC_SPORTS_PROFILE_CUSTOMER';
const COLUMNS = [
  'CRMID', 'ECID', 'EMAIL', 'EMAILIDSHA256', 'GAID', 'LOYALTYID', 'PHONENUMBER', 'PUSHTOKENS', 'STACKCHATID',
  'FIRSTNAME', 'LASTNAME', 'DATEOFBIRTH', 'GENDER', 'NATIONALITY', 'PRIMARYEMAIL', 'PRIMARYPHONE',
  'ADDRESSSTREET', 'ADDRESSCITY', 'ADDRESSPOSTALCODE', 'ADDRESSCOUNTRY', 'LIFETIMEVALUE', 'CUSTOMERSEGMENT',
  'FAVOURITESPORT', 'FAVOURITETEAM', 'FANSEGMENT', 'SEASONTICKET', 'LASTATTENDEDDATE', 'LASTEVENTNAME',
  'MERCHSPENDYTD', 'JERSEYSIZEPREFERENCE', 'FANTASYLEAGUE', 'BETSREGULARLY', 'STREAMLIVE',
  'NEWSLETTERSUBSCRIBED', 'LASTPURCHASEITEM', 'STADIUMSECTION', 'MEMBERSHIPTYPE',
  'TESTPROFILE', '_RECORDCREATEDTIMESTAMP', '_RECORDUPDATEDTIMESTAMP',
];
const NUMBER_COLUMNS = new Set(['LIFETIMEVALUE', 'MERCHSPENDYTD']);
const BOOL_COLUMNS = new Set([
  'TESTPROFILE', 'SEASONTICKET', 'FANTASYLEAGUE', 'BETSREGULARLY', 'STREAMLIVE', 'NEWSLETTERSUBSCRIBED',
]);
const COLUMN_DDL = COLUMNS.map((column) => {
  if (column === 'PUSHTOKENS') return `${column} ARRAY`;
  if (BOOL_COLUMNS.has(column)) return `${column} BOOLEAN`;
  if (NUMBER_COLUMNS.has(column)) return `${column} NUMBER(18,2)`;
  return `${column} VARCHAR(320)`;
});

module.exports = { TABLE, COLUMNS, COLUMN_DDL };
